### ISSUE TITLE
Ui异常

### ISSUE THREAD

**Issue by woshigenm** [Xposed-Modules-Repo/com.hujiayucc.hook#1]
打开APP一直闪屏，黑屏
如图
![Screenshot_2023-02-19-13-04-16-064_com hujiayucc hook](https://user-images.githubusercontent.com/99122353/219923322-f9cbb73e-04d2-498f-9265-848a0e7a9c14.jpg)

[cat.log](https://github.com/Xposed-Modules-Repo/com.hujiayucc.hook/files/10776006/cat.log)

**Comment by hujiayucc** [comment]
1.0.2版本已修复

**Comment by hujiayucc** [comment]
1.0.2版本已修复
