### ISSUE TITLE
APP闪退问题

### ISSUE THREAD

**Issue by mazemingw** [Xposed-Modules-Repo/com.hujiayucc.hook#2]
NoTip版本打开后，勾选“自带跳过”则立即闪退，无法再次打开界面，需要清理数据才能重新打开。

另一个版本则是直接无法启动到主页面，已清理数据，但无效。
ColorOS13

**Comment by hujiayucc** [comment]
NoTip仅为适配LSPatch，LSPosed环境请使用正常版本
