### ISSUE TITLE
1.2.5 & 1.2.6 initial pop-pop

### ISSUE THREAD

**Issue by samuraikid0** [Xposed-Modules-Repo/com.hujiayucc.hook#3]
What do I need to do ? I cant go further the initial pop-pop

Version 1.2.4 works ok

Thanks

**Comment by traversone** [comment]
it is blocking indeed, it is a pity. Furthermore, on A11 version 1.2.6 cannot be installed at all!

**Comment by traversone** [comment]
every new version starting from 1.2.5 has this pop-up ! @developer: please tell us what to do to restore module functionality. Could you translate such pop-up into English and do you mind explaining what users are supposed to do with it? Thank you

**Comment by samuraikid0** [comment]
someone try to reach him on his other github he seems not read this repo

**Comment by samuraikid0** [comment]
Dev seems not to read issues from this repo
